name: ping_pong
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  authentication_repository:
    path: packages/authentication_repository
  firestore_repository:
    path: packages/firestore_repository
  equatable: ^2.0.3
  bloc: ^8.0.3
  formz: ^0.4.1
  form_inputs:
    path: packages/form_inputs
  flutter_bloc: ^8.0.1
  google_fonts: ^2.1.0
  font_awesome_flutter: ^10.1.0
  meta: ^1.3.0
  very_good_analysis: ^2.4.0
  go_router: ^3.1.0
  firebase_core: ^1.5.0
  cloud_firestore: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
